image:
  python:3.8-slim-buster
   
before_script:
  - pip3 install autopep8 \
    flake8 \
    numpy==1.20.1 \
    pandas==1.2.3 \
    matplotlib==3.3.4 \
    japanize-matplotlib==1.1.3 \
    sklearn \
    scipy==1.6.2 \
    seaborn==0.11.1 \
    pytest==6.2.2 \
    pytest-cov==2.11.1

test:
  script:
    - pytest -vv
